
SELECT count(*) TOTAL_REGISTROS
, SUM(CASE WHEN length(TRIM(BILL_REF_NO))<>0 THEN 1 ELSE 0 END) TOTAL_BILL_REF_NO
, COUNT(DISTINCT CASE WHEN length(TRIM(BILL_REF_NO))<>0 THEN BILL_REF_NO ELSE NULL END) TOTAL_DIS_BILL_REF_NO
, SUM(CASE WHEN length(TRIM(CUSTOMER_ID))<>0 THEN 1 ELSE 0 END) TOTAL_CUSTOMER_ID
, COUNT(DISTINCT CASE WHEN length(TRIM(CUSTOMER_ID))<>0 THEN CUSTOMER_ID ELSE NULL END) TOTAL_DIS_CUSTOMER_ID
, SUM(CASE WHEN length(TRIM(START_DATE))<>0 THEN 1 ELSE 0 END) TOTAL_START_DATE
, COUNT(DISTINCT CASE WHEN length(TRIM(START_DATE))<>0 THEN START_DATE ELSE NULL END) TOTAL_DIS_START_DATE
, SUM(CASE WHEN length(TRIM(END_DATE))<>0 THEN 1 ELSE 0 END) TOTAL_END_DATE
, COUNT(DISTINCT CASE WHEN length(TRIM(END_DATE))<>0 THEN END_DATE ELSE NULL END) TOTAL_DIS_END_DATE
, SUM(CASE WHEN length(TRIM(STATEMENT_DATE))<>0 THEN 1 ELSE 0 END) TOTAL_STATEMENT_DATE
, COUNT(DISTINCT CASE WHEN length(TRIM(STATEMENT_DATE))<>0 THEN STATEMENT_DATE ELSE NULL END) TOTAL_DIS_STATEMENT_DATE
, SUM(CASE WHEN length(TRIM(PAYMENT_DATE))<>0 THEN 1 ELSE 0 END) TOTAL_PAYMENT_DATE
, COUNT(DISTINCT CASE WHEN length(TRIM(PAYMENT_DATE))<>0 THEN PAYMENT_DATE ELSE NULL END) TOTAL_DIS_PAYMENT_DATE
, SUM(CASE WHEN length(TRIM(BILL_CYCLE))<>0 THEN 1 ELSE 0 END) TOTAL_BILL_CYCLE
, COUNT(DISTINCT CASE WHEN length(TRIM(BILL_CYCLE))<>0 THEN BILL_CYCLE ELSE NULL END) TOTAL_DIS_BILL_CYCLE
, SUM(CASE WHEN length(TRIM(AMOUNT))<>0 THEN 1 ELSE 0 END) TOTAL_AMOUNT
, COUNT(DISTINCT CASE WHEN length(TRIM(AMOUNT))<>0 THEN AMOUNT ELSE NULL END) TOTAL_DIS_AMOUNT
, SUM(CASE WHEN length(TRIM(BILL_METHOD))<>0 THEN 1 ELSE 0 END) TOTAL_BILL_METHOD
, COUNT(DISTINCT CASE WHEN length(TRIM(BILL_METHOD))<>0 THEN BILL_METHOD ELSE NULL END) TOTAL_DIS_BILL_METHOD
FROM STAGE.STG_FACTURAS_FCT;