
SELECT count(*) TOTAL_REGISTROS
, SUM(CASE WHEN length(TRIM(ID))<>0 THEN 1 ELSE 0 END) TOTAL_ID
, COUNT(DISTINCT CASE WHEN length(TRIM(ID))<>0 THEN ID ELSE NULL END) TOTAL_DIS_ID
, SUM(CASE WHEN length(TRIM(PHONE_NUMBER))<>0 THEN 1 ELSE 0 END) TOTAL_PHONE_NUMBER
, COUNT(DISTINCT CASE WHEN length(TRIM(PHONE_NUMBER))<>0 THEN PHONE_NUMBER ELSE NULL END) TOTAL_DIS_PHONE_NUMBER
, SUM(CASE WHEN length(TRIM(START_DATETIME))<>0 THEN 1 ELSE 0 END) TOTAL_START_DATETIME
, COUNT(DISTINCT CASE WHEN length(TRIM(START_DATETIME))<>0 THEN START_DATETIME ELSE NULL END) TOTAL_DIS_START_DATETIME
, SUM(CASE WHEN length(TRIM(END_DATETIME))<>0 THEN 1 ELSE 0 END) TOTAL_END_DATETIME
, COUNT(DISTINCT CASE WHEN length(TRIM(END_DATETIME))<>0 THEN END_DATETIME ELSE NULL END) TOTAL_DIS_END_DATETIME
, SUM(CASE WHEN length(TRIM(SERVICE))<>0 THEN 1 ELSE 0 END) TOTAL_SERVICE
, COUNT(DISTINCT CASE WHEN length(TRIM(SERVICE))<>0 THEN SERVICE ELSE NULL END) TOTAL_DIS_SERVICE
, SUM(CASE WHEN length(TRIM(FLG_TRANSFER))<>0 THEN 1 ELSE 0 END) TOTAL_FLG_TRANSFER
, COUNT(DISTINCT CASE WHEN length(TRIM(FLG_TRANSFER))<>0 THEN FLG_TRANSFER ELSE NULL END) TOTAL_DIS_FLG_TRANFER
, SUM(CASE WHEN length(TRIM(AGENT))<>0 THEN 1 ELSE 0 END) TOTAL_AGENT
, COUNT(DISTINCT CASE WHEN length(TRIM(AGENT))<>0 THEN AGENT ELSE NULL END) TOTAL_DIS_AGENT
FROM STAGE.STG_CONTACTOS_IVR;