
SELECT count(*) TOTAL_REGISTROS
, SUM(CASE WHEN length(TRIM(CUSTOMER_ID))<>0 THEN 1 ELSE 0 END) TOTAL_CUSTOMER_ID
, COUNT(DISTINCT CASE WHEN length(TRIM(CUSTOMER_ID))<>0 THEN CUSTOMER_ID ELSE NULL END) TOTAL_DIS_CUSTOMER_ID
, SUM(CASE WHEN length(TRIM(PRODUCT_ID))<>0 THEN 1 ELSE 0 END) TOTAL_PRODUCT_ID
, COUNT(DISTINCT CASE WHEN length(TRIM(PRODUCT_ID))<>0 THEN PRODUCT_ID ELSE NULL END) TOTAL_DIS_PRODUCT_ID
, SUM(CASE WHEN length(TRIM(PRODUCT_NAME))<>0 THEN 1 ELSE 0 END) TOTAL_PRODUCT_NAME
, COUNT(DISTINCT CASE WHEN length(TRIM(PRODUCT_NAME))<>0 THEN PRODUCT_NAME ELSE NULL END) TOTAL_DIS_PRODUCT_NAME
, SUM(CASE WHEN length(TRIM(ACCESS_POINT))<>0 THEN 1 ELSE 0 END) TOTAL_ACCESS_POINT
, COUNT(DISTINCT CASE WHEN length(TRIM(ACCESS_POINT))<>0 THEN ACCESS_POINT ELSE NULL END) TOTAL_DIS_ACCESS_POINT
, COUNT(DISTINCT length(TRIM(ACCESS_POINT))) TOTAL_DIS_ACCESS_POINT_LEN
, SUM(CASE WHEN length(TRIM(AGENT_CODE))<>0 THEN 1 ELSE 0 END) TOTAL_AGENT_CODE
, COUNT(DISTINCT CASE WHEN length(TRIM(AGENT_CODE))<>0 THEN AGENT_CODE ELSE NULL END) TOTAL_DIS_AGENT_CODE
, SUM(CASE WHEN length(TRIM(`CHANNEL`))<>0 THEN 1 ELSE 0 END) TOTAL_CHANNEL
, COUNT(DISTINCT CASE WHEN length(TRIM(`CHANNEL`))<>0 THEN `CHANNEL` ELSE NULL END) TOTAL_DIS_CHANNEL
, SUM(CASE WHEN length(TRIM(START_DATE))<>0 THEN 1 ELSE 0 END) TOTAL_START_DATE
, COUNT(DISTINCT CASE WHEN length(TRIM(START_DATE))<>0 THEN START_DATE ELSE NULL END) TOTAL_DIS_START_DATE
, SUM(CASE WHEN length(TRIM(INSTALL_DATE))<>0 THEN 1 ELSE 0 END) TOTAL_INSTALL_DATE
, COUNT(DISTINCT CASE WHEN length(TRIM(INSTALL_DATE))<>0 THEN INSTALL_DATE ELSE NULL END) TOTAL_DIS_INSTALL_DATE
, SUM(CASE WHEN length(TRIM(PRODUCT_CITY))<>0 THEN 1 ELSE 0 END) TOTAL_PRODUCT_CITY
, COUNT(DISTINCT CASE WHEN length(TRIM(PRODUCT_CITY))<>0 THEN PRODUCT_CITY ELSE NULL END) TOTAL_DIS_PRODUCT_CITY
, SUM(CASE WHEN length(TRIM(PRODUCT_ADDRESS))<>0 THEN 1 ELSE 0 END) TOTAL_PRODUCT_ADDRESS
, COUNT(DISTINCT CASE WHEN length(TRIM(PRODUCT_ADDRESS))<>0 THEN PRODUCT_ADDRESS ELSE NULL END) TOTAL_DIS_PRODUCT_ADDRESS
, SUM(CASE WHEN length(TRIM(PRODUCT_POSTAL_CODE))<>0 THEN 1 ELSE 0 END) TOTAL_PRODUCT_POSTAL_CODE
, COUNT(DISTINCT CASE WHEN length(TRIM(PRODUCT_POSTAL_CODE))<>0 THEN PRODUCT_POSTAL_CODE ELSE NULL END) TOTAL_DIS_PRODUCT_POSTAL_CODE
, SUM(CASE WHEN length(TRIM(PRODUCT_STATE))<>0 THEN 1 ELSE 0 END) TOTAL_PRODUCT_STATE
, COUNT(DISTINCT CASE WHEN length(TRIM(PRODUCT_STATE))<>0 THEN PRODUCT_STATE ELSE NULL END) TOTAL_DIS_PRODUCT_STATE
, SUM(CASE WHEN length(TRIM(PRODUCT_COUNTRY))<>0 THEN 1 ELSE 0 END) TOTAL_PRODUCT_COUNTRY
, COUNT(DISTINCT CASE WHEN length(TRIM(PRODUCT_COUNTRY))<>0 THEN PRODUCT_COUNTRY ELSE NULL END) TOTAL_DIS_PRODUCT_COUNTRY
FROM STAGE.STG_PRODUCTOS_CRM;

