USE ODS;
-- CREAR TABLAS ODS
-- +++++++++++++++

DROP TABLE IF EXISTS ODS_HC_SERVICIOS;
CREATE TABLE ODS_HC_SERVICIOS
(ID_SERVICIO INT NOT NULL PRIMARY KEY,
ID_CLIENTE INT UNSIGNED NOT NULL,
ID_PRODUCTO INT UNSIGNED NOT NULL,
PUNTO_ACCESO VARCHAR(512),
ID_CANAL INT UNSIGNED,
ID_AGENTE INT,
ID_DIRECCION_SERVICIO INT UNSIGNED,
FC_INICIO DATETIME,
FC_INSTALACION DATETIME,
FC_FIN DATETIME,
FC_INSERT DATETIME,
FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_DM_PRODUCTOS;
CREATE TABLE ODS_DM_PRODUCTOS 
(ID_PRODUCTO INT unsigned auto_increment primary KEY,
DE_PRODUCTO VARCHAR(512),
FC_INSERT DATETIME,
FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_DM_CANALES;
CREATE TABLE ODS_DM_CANALES 
(ID_CANAL INT unsigned auto_increment primary KEY,
DE_CANAL VARCHAR(512),
FC_INSERT DATETIME,
FC_MODIFICACION DATETIME);


-- CREAR FOREING KEYS
-- ++++++++++++++++++

ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_serv_prod_idx (ID_PRODUCTO ASC);
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_prod FOREIGN KEY (ID_PRODUCTO) 
	REFERENCES ODS_DM_PRODUCTOS (ID_PRODUCTO);
    
ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_serv_canal_idx (ID_CANAL ASC);
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_canal FOREIGN KEY (ID_CANAL) 
	REFERENCES ODS_DM_CANALES (ID_CANAL);
    
ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_serv_cli_idx (ID_CLIENTE ASC);
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_cli FOREIGN KEY (ID_CLIENTE) 
	REFERENCES ODS_HC_CLIENTES (ID_CLIENTE);
    
ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_serv_dir_idx (ID_DIRECCION_SERVICIO ASC);
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_cli FOREIGN KEY (ID_DIRECCION_SERVICIO) 
	REFERENCES ODS_HC_DIRECCIONES (ID_DIRECCION);

