USE ODS;

-- CREAR TABLAS ODS
-- +++++++++++++++

DROP TABLE IF EXISTS ODS_DM_FASES;
CREATE TABLE ODS_DM_FASES
(ID_FASE INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
DE_FASE VARCHAR(512) NOT NULL,
FC_INSERT DATETIME NOT NULL,
FC_MODIFICACION DATETIME NOT NULL);

DROP TABLE IF EXISTS ODS_HC_ORDENES;
CREATE TABLE ODS_HC_ORDENES
(ID_ORDEN INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
ID_ORDEN_CRM INT NOT NULL,
ID_SERVICIO INT NOT NULL,
ID_FASE INT UNSIGNED NOT NULL,
ID_AGENTE INT UNSIGNED NOT NULL,
FC_INICIO DATETIME NOT NULL,
FC_FIN DATETIME NOT NULL,
FC_INSERT DATETIME NOT NULL,
FC_MODIFICACION DATETIME NOT NULL);


ALTER TABLE ODS_HC_ORDENES ADD INDEX fk_ord_fase_idx (ID_FASE ASC);
ALTER TABLE ODS_HC_ORDENES ADD CONSTRAINT fk_ord_fase FOREIGN KEY (ID_FASE) 
	REFERENCES ODS_DM_FASES (ID_FASE);
    
ALTER TABLE ODS_HC_ORDENES ADD INDEX fk_ord_agente_idx (ID_AGENTE ASC);
ALTER TABLE ODS_HC_ORDENES ADD CONSTRAINT fk_ord_agente FOREIGN KEY (ID_AGENTE) 
	REFERENCES ODS_DM_AGENTES (ID_AGENTE);

ALTER TABLE ODS_HC_ORDENES ADD INDEX fk_ord_serv_idx (ID_SERVICIO ASC);
ALTER TABLE ODS_HC_ORDENES ADD CONSTRAINT fk_ord_serv FOREIGN KEY (ID_SERVICIO) 
	REFERENCES ODS_HC_SERVICIOS (ID_SERVICIO);