USE ODS;

-- CREAR TABLAS ODS
-- +++++++++++++++

DROP TABLE IF EXISTS ODS_DM_DEPARTAMENTOS;
CREATE TABLE ODS_DM_DEPARTAMENTOS
(ID_DEPARTAMENTO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
DE_DEPARTAMENTO VARCHAR(512),
FC_INSERT DATETIME,
FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_DM_AGENTES;
CREATE TABLE ODS_DM_AGENTES
(ID_AGENTE INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
DE_AGENTE VARCHAR(512),
FC_INSERT DATETIME,
FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_HC_LLAMADAS;
CREATE TABLE ODS_HC_LLAMADAS
(ID_LLAMADA INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
ID_IVR INT,
TELEFONO_LLAMADA BIGINT(20),
FC_INICIO_LLAMADA DATETIME,
FC_FIN_LLAMADA DATETIME,
ID_DEPARTAMENTO INT UNSIGNED,
FLG_TRANSFERIDO TINYINT(1),
ID_AGENTE INT UNSIGNED,
FC_INSERT DATETIME,
FC_MODIFICACION DATETIME);

-- CREAR FOREING KEYS
-- ++++++++++++++++++

ALTER TABLE ODS_HC_LLAMADAS ADD INDEX fk_llam_dep_idx (ID_DEPARTAMENTO ASC);
ALTER TABLE ODS_HC_LLAMADAS ADD CONSTRAINT fk_llam_dep FOREIGN KEY (ID_DEPARTAMENTO) 
	REFERENCES ODS_DM_DEPARTAMENTOS (ID_DEPARTAMENTO);
    
ALTER TABLE ODS_HC_LLAMADAS ADD INDEX fk_llam_agente_idx (ID_AGENTE ASC);
ALTER TABLE ODS_HC_LLAMADAS ADD CONSTRAINT fk_llam_agente FOREIGN KEY (ID_AGENTE) 
	REFERENCES ODS_DM_AGENTES (ID_AGENTE);
