USE ODS;

-- POBLAR TABLA FASES
-- ++++++++++++++++++++

INSERT INTO ODS_DM_FASES (DE_FASE, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(`PHASE`)), NOW(), NOW() 
FROM STAGE.STG_ORDERS_CRM
WHERE LENGTH(TRIM(`PHASE`)) > 0;

INSERT INTO ODS_DM_FASES VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_FASES VALUES (98, 'NO APLICA', NOW(), NOW());

ANALYZE TABLE ODS_DM_FASES;

-- AÑADIR NUEVOS AGENTES A LA TABLA DE AGENTES
-- +++++++++++++++++++++++++++++++++++++++++++

SELECT @max := (max(ID_AGENTE)) from ODS_DM_AGENTES
WHERE ID_AGENTE < 9998;    

INSERT INTO ODS_DM_AGENTES (ID_AGENTE, DE_AGENTE, FC_INSERT, FC_MODIFICACION)
SELECT @rownum:=@rownum+1 AS ID_AGENTE, AGENTE, NOW(), NOW() FROM 
(SELECT @rownum:=@max) R,
(SELECT DISTINCT UPPER(TRIM(AGENT)) AGENTE 
FROM STAGE.STG_ORDERS_CRM
LEFT JOIN ODS.ODS_DM_AGENTES ON ODS_DM_AGENTES.DE_AGENTE = UPPER(TRIM(AGENT))
WHERE LENGTH(TRIM(AGENT)) > 0 AND ODS_DM_AGENTES.ID_AGENTE IS NULL) A;

ANALYZE TABLE ODS_DM_AGENTES;


-- AÑADIR NUEVOS SERVICIOS A LA TABLA DE SERVICIOS
-- +++++++++++++++++++++++++++++++++++++++++++++++


-- 
INSERT INTO ODS_HC_SERVICIOS (ID_SERVICIO,
ID_CLIENTE,
ID_PRODUCTO,
PUNTO_ACCESO,
ID_CANAL,
ID_AGENTE,
FC_INICIO,
FC_INSTALACION,
FC_FIN,
ID_DIRECCION_SERVICIO,
FC_INSERT,
FC_MODIFICACION)
SELECT 
9999000000 + `ORDER` ID_SERVICIO,
999999999 ID_CLIENTE,
999 ID_PRODUCTO,
99999999999999999999 PUNTO_ACCESO,
999 ID_CANAL,
9999 ID_AGENTE,
str_to_date("31/12/9999", "%d/%m/%Y") FC_INICIO,
str_to_date("31/12/9999", "%d/%m/%Y") FC_INSTALACION,
str_to_date("31/12/9999", "%d/%m/%Y") FC_FIN,
999999,
NOW(),
NOW()
FROM STAGE.STG_ORDERS_CRM ORDENES
LEFT JOIN ODS_HC_SERVICIOS ON ORDENES.`ORDER` = ODS_HC_SERVICIOS.ID_SERVICIO
WHERE lENGTH(TRIM(ORDENES.`ORDER`)) > 0 AND ODS_HC_SERVICIOS.ID_SERVICIO IS NULL;

ANALYZE TABLE ODS_DM_AGENTES;

-- POBLAR TABLA ORDENES
-- ++++++++++++++++++++

INSERT INTO ODS_HC_ORDENES
(ID_ORDEN_CRM,
ID_SERVICIO,
ID_FASE,
ID_AGENTE,
FC_INICIO,
FC_FIN,
FC_INSERT,
FC_MODIFICACION)
SELECT
ID ID_ORDEN_CRM,
`ORDER` ID_SERVICIO,
IFNULL(ID_FASE, 99) ID_FASE,
IFNULL(ODS_DM_AGENTES.ID_AGENTE, 9999) ID_AGENTE,
 CASE WHEN LENGTH(TRIM(START_DT)) > 0 THEN IFNULL(str_to_date(START_DT, "%Y-%m-%d %H:%i:%s.%f"), str_to_date("31/12/9999", "%d/%m/%Y"))
		ELSE str_to_date("31/12/9999", "%d/%m/%Y") END FC_INICIO,
 CASE WHEN LENGTH(TRIM(END_DT)) > 0 THEN IFNULL(str_to_date(END_DT, "%Y-%m-%d %H:%i:%s.%f"), str_to_date("31/12/9999", "%d/%m/%Y"))
		ELSE str_to_date("31/12/9999", "%d/%m/%Y") END FC_FIN,
NOW(),
NOW()
FROM STAGE.STG_ORDERS_CRM ORDENES
LEFT JOIN ODS_HC_SERVICIOS ON ORDENES.`ORDER` = ODS_HC_SERVICIOS.ID_SERVICIO
LEFT JOIN ODS_DM_FASES ON UPPER(TRIM(`PHASE`)) = ODS_DM_FASES.DE_FASE
LEFT JOIN ODS_DM_AGENTES ON UPPER(TRIM(AGENT)) = ODS_DM_AGENTES.DE_AGENTE;
	
